# Production environment configuration for Firebase App Hosting
# This file overrides values from .apphosting.yaml
# See: https://firebase.google.com/docs/app-hosting/multiple-environments

runConfig:
  runtime: nodejs20
  # Production: More resources for better performance
  cpu: 2
  memoryMiB: 2048
  maxInstances: 10
  minInstances: 1
  concurrency: 100

env:
  # Production environment variables
  - variable: NODE_ENV
    value: production
    availability:
      - BUILD
      - RUNTIME

  - variable: NEXT_TELEMETRY_DISABLED
    value: "1"
    availability:
      - BUILD
      - RUNTIME

  # Production URLs
  - variable: NEXT_PUBLIC_BASE_URL
    value: https://palkamtm.pl
    availability:
      - BUILD
      - RUNTIME

  - variable: NEXTAUTH_URL
    value: https://palkamtm.pl
    availability:
      - RUNTIME

  # Database - dodaj później (pominięte na razie)
  # Format dla MySQL: mysql://username:password@host:3306/database_name
  # Format dla PostgreSQL: postgresql://username:password@host:5432/database_name
  # - variable: DATABASE_URL
  #   value: mysql://username:password@host:3306/database_name
  #   availability:
  #     - RUNTIME

  # NextAuth Secret - wygenerowany secret
  - variable: NEXTAUTH_SECRET
    value: wByeVufjYdavIMUhPsntG/CA0H6MvplAb6T/db6yf8U=
    availability:
      - RUNTIME

  # Firebase Client-side (from env.production)
  - variable: NEXT_PUBLIC_FIREBASE_API_KEY
    value: AIzaSyCrGcWptUnRgcNnAQl01g5RjPdMfZ2tJCA
    availability:
      - BUILD
      - RUNTIME

  - variable: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
    value: m-t-m-62972.firebaseapp.com
    availability:
      - BUILD
      - RUNTIME

  - variable: NEXT_PUBLIC_FIREBASE_PROJECT_ID
    value: m-t-m-62972
    availability:
      - BUILD
      - RUNTIME

  - variable: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
    value: m-t-m-62972.firebasestorage.app
    availability:
      - BUILD
      - RUNTIME

  - variable: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
    value: "714609522899"
    availability:
      - BUILD
      - RUNTIME

  - variable: NEXT_PUBLIC_FIREBASE_APP_ID
    value: 1:714609522899:web:462e995a1f358b1b0c3c26
    availability:
      - BUILD
      - RUNTIME

  - variable: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
    value: G-T645E1YQHW
    availability:
      - BUILD
      - RUNTIME

  # Firebase Admin SDK (Server-side)
  - variable: FIREBASE_PROJECT_ID
    value: m-t-m-62972
    availability:
      - RUNTIME

  - variable: FIREBASE_CLIENT_EMAIL
    value: firebase-adminsdk-fbsvc@m-t-m-62972.iam.gserviceaccount.com
    availability:
      - RUNTIME

  - variable: FIREBASE_PRIVATE_KEY
    value: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCcRe0BslSnISuR\nFcisDVbgkNvz3jekt/z9KI6LsR4ddyBfyH2up0BcEvLuNXwUTsTKxmTSbn1HoG7m\nnzDIJrzwL0xLBhzujhAbCfPg0nHYqifiVu0QY27nGh+2MltN9q99rDcdVQfVDSsj\nXwiD1py2oX1l5o6PeKsifenacG5tATcexfjnPuxxLdTFyF1LhgMwVNyoPKOvpEsd\nbGG8pWtAXW5xiyJTvHcYI5T0I8oLugNCKYazEWbD0Cz5ZCWUDFuo7jHitU+PYhvN\nsvEiDMySOhmjvdHqR+JvvcBxOnS9241KjTbeZ1adaFLg1E+FxQVfBOkJuJQY4ylX\nvHSrXss9AgMBAAECggEAQfUtlJK9MhFI/yKPoTa8HWpmu6ZmG+rgJ8XPbFxkVpFq\nI6NOkMHc4z/IMwx2A2g/nUphUYP68plfVY2JHGFlS4bbD6tT2MgzOgZYXeLU1Fr1\nHI4N3uXo8DfRfKgCa4ScC1H9rS6vcJfvRi2dPW/+kwLUF4dZUmre6F72rhDYOr8o\nhEQW3LAAgBdm40xWJo8gIRKKtGM7xl0o2CCrilt7XY0DqZrZVnYrNOrphCCt7e4g\nhkhzhDnL5P5Q6B4Vc0kY2xg3/c9Hb5QnBHzMV/N7d6rl3zMrQ7t9B7R8s0BudKRH\n5qtnBr3VjMzYolmpDAp626r55MjPqG2IWdBoSANRzQKBgQDSQCeKegcfM+g2UIOL\nPDwae4PR3BRTOdyvGMcv+lxeXXXE/b2ostiaKKimTKHtRCizozFz7v3gR6MHCCtP\nZqPh3Hya5r0HpslSN2j028wKi2Zj144tWCzyHjArZOsUBXJrh3b/RLrVhobOggDs\nMS4JJUDh+PAM5isX6B+V4Bf6HwKBgQC+Rv/Wi+F4XvhQG9rnOgZ7Cwdx0IRhb/Mi\nIzpeOCC9D/3HeDQHfnwjGJugNZiXibdv4TmjDYxPXWIiK+hQTT1rrt+jm5F3Qgyg\nJ/tBaTEc/eSDFsx9oIIWPk6sQKeUbUXDjCyzPpj7oxIS1FLE1WnJBFH3BQ9hLT9i\n24I72SdHIwKBgQDDA+apNw6sDoVw+7VHzJMjLTXTzgK8P4tGjgETq3FJxf6avZDR\njTIDq3ri5Wm8nd/y34fbNO4evdOljho+B8IymUSqmSL0metaazLbC5Ryo2JRcXra\n7FKkMQQU/AJgC71Zp8jkdWem7qTTnxoj+mns6bUI5NIj5MpL3m6NodIbmQKBgQC4\nccp+BopBTI4X2WiQy8aMb1yAD0jDyuk8JjnmKzJRErdGLFcDDLD4tFnnKw0HmA+g\n/AoK7I8eP79osHc5oCXxxEo1JhAUMopalWcROQ7Ks7JXADqpbHWtaiiJAQNw9Zuy\nuqZ5+iwBgUl7xyWUd+tbWDy73sPRxzKyeWX87bsNUQKBgEuRLuP3I2yJP1GzDClB\n3a0bc19XuXaGmxn0LBzHfqiqkq6lymWUIlFH5r+jibP9dDyvSHE9GWCkmVdfVhAf\nZUhXKc+ChCX0EWEb90+LhpIIY2pMZGg4gVn6NAW/xV3pyueGdDm1ciBPisrqWHMj\nJkH3fKiQfGi52ouES8nVl/tL\n-----END PRIVATE KEY-----\n"
    availability:
      - RUNTIME

  # SMS Provider
  - variable: SMS_PROVIDER
    value: firebase
    availability:
      - RUNTIME

buildConfig:
  commands:
    - npm ci
    - npm run build
  env:
    - variable: NODE_ENV
      value: production
    - variable: NEXT_TELEMETRY_DISABLED
      value: "1"

