# Production environment configuration for Firebase App Hosting
# This file overrides values from .apphosting.yaml
# See: https://firebase.google.com/docs/app-hosting/multiple-environments

runConfig:
  runtime: nodejs20
  # Production: More resources for better performance
  cpu: 2
  memoryMiB: 2048
  maxInstances: 10
  minInstances: 1
  concurrency: 100

env:
  # Production environment variables
  - variable: NODE_ENV
    value: production
    availability:
      - BUILD
      - RUNTIME

  - variable: NEXT_TELEMETRY_DISABLED
    value: "1"
    availability:
      - BUILD
      - RUNTIME

  # Production URLs
  - variable: NEXT_PUBLIC_BASE_URL
    value: https://palkamtm.pl
    availability:
      - BUILD
      - RUNTIME

  - variable: NEXTAUTH_URL
    value: https://palkamtm.pl
    availability:
      - RUNTIME

  # Database - ustaw prawdziwy connection string PostgreSQL
  - variable: DATABASE_URL
    value: postgresql://username:password@host:5432/palkamtm_production
    availability:
      - RUNTIME

  # NextAuth Secret - wygeneruj nowy secret (użyj: openssl rand -base64 32)
  - variable: NEXTAUTH_SECRET
    value: your-production-secret-key-here-change-this
    availability:
      - RUNTIME

  # Firebase Client-side (from env.production)
  - variable: NEXT_PUBLIC_FIREBASE_API_KEY
    value: AIzaSyCrGcWptUnRgcNnAQl01g5RjPdMfZ2tJCA
    availability:
      - BUILD
      - RUNTIME

  - variable: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
    value: m-t-m-62972.firebaseapp.com
    availability:
      - BUILD
      - RUNTIME

  - variable: NEXT_PUBLIC_FIREBASE_PROJECT_ID
    value: m-t-m-62972
    availability:
      - BUILD
      - RUNTIME

  - variable: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
    value: m-t-m-62972.firebasestorage.app
    availability:
      - BUILD
      - RUNTIME

  - variable: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
    value: "714609522899"
    availability:
      - BUILD
      - RUNTIME

  - variable: NEXT_PUBLIC_FIREBASE_APP_ID
    value: 1:714609522899:web:462e995a1f358b1b0c3c26
    availability:
      - BUILD
      - RUNTIME

  - variable: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
    value: G-T645E1YQHW
    availability:
      - BUILD
      - RUNTIME

  # Firebase Admin SDK - use secrets in Firebase Console
  # - variable: FIREBASE_PROJECT_ID
  #   value: m-t-m-62972
  #   availability:
  #     - RUNTIME

  # - variable: FIREBASE_CLIENT_EMAIL
  #   value: firebase-adminsdk-fbsvc@m-t-m-62972.iam.gserviceaccount.com
  #   availability:
  #     - RUNTIME

  # - variable: FIREBASE_PRIVATE_KEY
  #   secret: secretProductionFirebasePrivateKey
  #   availability:
  #     - RUNTIME

  # SMS Provider
  - variable: SMS_PROVIDER
    value: firebase
    availability:
      - RUNTIME

buildConfig:
  commands:
    - npm ci
    - npm run build
  env:
    - variable: NODE_ENV
      value: production
    - variable: NEXT_TELEMETRY_DISABLED
      value: "1"

