# Staging environment configuration for Firebase App Hosting
# This file overrides values from .apphosting.yaml
# See: https://firebase.google.com/docs/app-hosting/multiple-environments

runConfig:
  runtime: nodejs20
  # Staging: Fewer resources for cost savings
  cpu: 1
  memoryMiB: 1024
  maxInstances: 3
  minInstances: 0
  concurrency: 50

env:
  # Staging environment variables
  - variable: NODE_ENV
    value: production
    availability:
      - BUILD
      - RUNTIME

  - variable: NEXT_TELEMETRY_DISABLED
    value: "1"
    availability:
      - BUILD
      - RUNTIME

  # Staging URLs (adjust based on your staging domain)
  - variable: NEXT_PUBLIC_BASE_URL
    value: https://staging.palkamtm.pl
    availability:
      - BUILD
      - RUNTIME

  - variable: NEXTAUTH_URL
    value: https://staging.palkamtm.pl
    availability:
      - RUNTIME

  # Database - use secret in Firebase Console for staging
  # - variable: DATABASE_URL
  #   secret: secretStagingDatabaseURL
  #   availability:
  #     - RUNTIME

  # NextAuth Secret - use secret in Firebase Console for staging
  # - variable: NEXTAUTH_SECRET
  #   secret: secretStagingNextAuthSecret
  #   availability:
  #     - RUNTIME

  # Firebase Client-side (can use same as production or different)
  - variable: NEXT_PUBLIC_FIREBASE_API_KEY
    value: AIzaSyCrGcWptUnRgcNnAQl01g5RjPdMfZ2tJCA
    availability:
      - BUILD
      - RUNTIME

  - variable: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
    value: m-t-m-62972.firebaseapp.com
    availability:
      - BUILD
      - RUNTIME

  - variable: NEXT_PUBLIC_FIREBASE_PROJECT_ID
    value: m-t-m-62972
    availability:
      - BUILD
      - RUNTIME

  - variable: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
    value: m-t-m-62972.appspot.com
    availability:
      - BUILD
      - RUNTIME

  - variable: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
    value: "714609522899"
    availability:
      - BUILD
      - RUNTIME

  - variable: NEXT_PUBLIC_FIREBASE_APP_ID
    value: 1:714609522899:web:462e995a1f358b1b0c3c26
    availability:
      - BUILD
      - RUNTIME

  - variable: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
    value: G-T645E1YQHW
    availability:
      - BUILD
      - RUNTIME

  # Firebase Admin SDK - use secrets in Firebase Console
  # - variable: FIREBASE_PROJECT_ID
  #   value: m-t-m-62972
  #   availability:
  #     - RUNTIME

  # - variable: FIREBASE_CLIENT_EMAIL
  #   value: firebase-adminsdk-fbsvc@m-t-m-62972.iam.gserviceaccount.com
  #   availability:
  #     - RUNTIME

  # - variable: FIREBASE_PRIVATE_KEY
  #   secret: secretStagingFirebasePrivateKey
  #   availability:
  #     - RUNTIME

  # SMS Provider
  - variable: SMS_PROVIDER
    value: firebase
    availability:
      - RUNTIME

buildConfig:
  commands:
    - npm ci
    - npm run build
  env:
    - variable: NODE_ENV
      value: production
    - variable: NEXT_TELEMETRY_DISABLED
      value: "1"

